export const carsModel = [
  {
    id: 1,
    carFactoryId: 1,
    label: "audi car",
    value: "audi",
  },
  {
    id: 2,
    carFactoryId: 1,
    label: "bmw audi car",
    value: "bmw",
  },
  {
    id: 3,
    carFactoryId: 2,
    label: "buick bmw car",
    value: "buick",
  },
  {
    id: 4,
    carFactoryId: 2,
    label: "changan  bmw car",
    value: "changan",
  },
  {
    id: 5,
    carFactoryId: 2,
    label: "cherry  bmw car",
    value: "cherry",
  },
  {
    id: 6,
    carFactoryId: 5,
    label: "chevrolet",
    value: "chevrolet",
  },
  {
    id: 7,
    carFactoryId: 3,
    label: "chrysler",
    value: "chrysler",
  },
  {
    id: 8,
    carFactoryId: 3,
    label: "citroen",
    value: "citroen",
  },
  {
    id: 9,
    carFactoryId: 3,
    label: "daewoo",
    value: "daewoo",
  },
  {
    id: 10,
    carFactoryId: 4,
    label: "daihatsu",
    value: "daihatsu",
  },
  {
    id: 11,
    carFactoryId: 4,
    label: "dodge",
    value: "dodge",
  },
  {
    id: 12,
    carFactoryId: 1,
    label: "faw audi car",
    value: "faw",
  },
  {
    id: 13,
    carFactoryId: 4,
    label: "ferrari",
    value: "ferrari",
  },
  {
    id: 14,
    carFactoryId: 1,
    label: "fiat audi car",
    value: "fiat",
  },
  {
    id: 15,
    carFactoryId: 1,
    label: "ford audi car",
    value: "ford",
  },
  {
    id: 16,
    carFactoryId: 1,
    label: "GAC audi car",
    value: "GAC",
  },
  {
    id: 17,
    carFactoryId: 1,
    label: "geely audi car",
    value: "geely",
  },
  {
    id: 18,
    carFactoryId: 1,
    label: "gmc audi car",
    value: "gmc",
  },
  {
    id: 19,
    carFactoryId: 1,
    label: "greatwall audi car",
    value: "greatwall",
  },
  {
    id: 20,
    carFactoryId: 1,
    label: "haval audi car",
    value: "haval",
  },
  {
    id: 21,
    carFactoryId: 1,
    label: "honda audi car",
    value: "honda",
  },
  {
    id: 22,
    carFactoryId: 1,
    label: "hummer audi car",
    value: "hummer",
  },
  {
    id: 23,
    carFactoryId: 1,
    label: "hyundai audi car",
    value: "hyundai",
  },
  {
    id: 24,
    carFactoryId: 1,
    label: "infinity audi car",
    value: "infinity",
  },
  {
    id: 25,
    carFactoryId: 1,
    label: "jeep audi car",
    value: "jeep",
  },
  {
    id: 26,
    carFactoryId: 1,
    label: "kia audi car",
    value: "kia",
  },
  {
    id: 27,
    carFactoryId: 1,
    label: "land audi car",
    value: "land",
  },
  {
    id: 28,
    carFactoryId: 1,
    label: "mazda audi car",
    value: "mazda",
  },
  {
    id: 29,
    carFactoryId: 1,
    label: "mercedes audi car",
    value: "mercedes",
  },
  {
    id: 30,
    carFactoryId: 1,
    label: "mitsubishi audi car",
    value: "mitsubishi",
  },
  {
    id: 31,
    carFactoryId: 1,
    label: "nissan audi car",
    value: "nissan",
  },
  {
    id: 32,
    carFactoryId: 1,
    label: "porsche audi car",
    value: "porsche",
  },
  {
    id: 33,
    carFactoryId: 1,
    label: "suzuki audi car",
    value: "suzuki",
  },
  {
    id: 34,
    carFactoryId: 1,
    label: "toyota audi car",
    value: "toyota",
  },
  {
    id: 35,
    carFactoryId: 1,
    label: "volkswagen audi car",
    value: "volkswagen",
  },
  {
    id: 36,
    carFactoryId: 1,
    label: "astonmartin audi car",
    value: "astonmartin",
  },
  {
    id: 40,
    carFactoryId: 1,
    label: "cadillac audi car",
    value: "cadillac",
  },
];
