export const cars = [
  {
    id: 1,
    enLabel: "audi",
    arLabel: "أودي",
    logo: "/carlogo/audi-logo.png",
  },
  {
    id: 2,
    enLabel: "bmw",
    arLabel: "بي ام ",
    logo: "/carlogo/bmw-logo.png",
  },
  {
    id: 3,
    enLabel: "buick",
    arLabel: "بويك",
    logo: "/carlogo/buick-logo.png",
  },
  {
    id: 4,
    enLabel: "changan",
    arLabel: "شانجان",

    logo: "/carlogo/changan-logo.png",
  },
  {
    id: 5,
    enLabel: "cherry",
    arLabel: "شيري",
    logo: "/carlogo/cherry-logo.png",
  },
  {
    id: 6,
    enLabel: "chevrolet",
    arLabel: "شيفرولي",
    logo: "/carlogo/chevrolet-logo.png",
  },
  {
    id: 7,
    enLabel: "chrysler",
    arLabel: "كريسلر",

    logo: "/carlogo/chrysler-logo.png",
  },
  {
    id: 8,
    enLabel: "citroen",
    arLabel: "سيتروين",
    logo: "/carlogo/citroen-logo.png",
  },
  {
    id: 9,
    enLabel: "daewoo",
    arLabel: "دائو",
    logo: "/carlogo/daewoo-logo.png",
  },
  {
    id: 10,
    enLabel: "daihatsu",
    arLabel: "ديهاتسو",
    logo: "/carlogo/daihatsu-logo.png",
  },
  {
    id: 11,
    enLabel: "dodge",
    arLabel: "دودج",
    logo: "/carlogo/dodge-logo.png",
  },
  {
    id: 12,
    enLabel: "faw",
    arLabel: "فاو",
    logo: "/carlogo/faw-logo.png",
  },
  {
    id: 13,
    enLabel: "ferrari",
    arLabel: "فيراري",
    logo: "/carlogo/ferrari-logo.png",
  },
  {
    id: 14,
    enLabel: "fiat",
    arLabel: "فيات",
    logo: "/carlogo/fiat-logo.png",
  },
  {
    id: 15,
    enLabel: "ford",
    arLabel: "فورد",
    logo: "/carlogo/ford-logo.png",
  },
  {
    id: 16,
    enLabel: "GAC",
    arLabel: "جاك",
    logo: "/carlogo/GAC-logo.png",
  },
  {
    id: 17,
    enLabel: "geely",
    arLabel: "جيلي",
    logo: "/carlogo/geely-logo.png",
  },
  {
    id: 18,
    enLabel: "gmc",
    arLabel: "جيمس",
    logo: "/carlogo/gmc-logo.png",
  },
  {
    id: 19,
    enLabel: "greatwall",
    arLabel: "غريتول",
    logo: "/carlogo/greatwall-logo.png",
  },
  {
    id: 20,
    enLabel: "haval",
    arLabel: "هافل",
    logo: "/carlogo/haval-logo.png",
  },
  {
    id: 21,
    enLabel: "honda",
    arLabel: "هوندا",
    logo: "/carlogo/honda-logo.png",
  },
  {
    id: 22,
    enLabel: "hummer",
    arLabel: "هامر",
    logo: "/carlogo/hummer-icon.png",
  },
  {
    id: 23,
    enLabel: "hyundai",
    arLabel: "هيونداي",
    logo: "/carlogo/hyundai-icon.png",
  },
  {
    id: 24,
    enLabel: "infinity",
    arLabel: "انفنتي",
    logo: "/carlogo/infinity-icon.png",
  },
  {
    id: 25,
    enLabel: "jeep",
    arLabel: "جيب",
    logo: "/carlogo/jeep-icon.png",
  },
  {
    id: 26,
    enLabel: "kia",
    arLabel: "كيا",
    logo: "/carlogo/kia-logo.png",
  },
  {
    id: 27,
    enLabel: "land",
    arLabel: "لاند",
    logo: "/carlogo/land-logo.png",
  },
  {
    id: 28,
    enLabel: "mazda",
    arLabel: "مازدا",
    logo: "/carlogo/mazda-logo.png",
  },
  {
    id: 29,
    enLabel: "mercedes",
    arLabel: "مرسيدس",
    logo: "/carlogo/mercedes-logo.png",
  },
  {
    id: 30,
    enLabel: "mitsubishi",
    arLabel: "ميتسوبيشي",
    logo: "/carlogo/mitsubishi-logo.png",
  },
  {
    id: 31,
    enLabel: "nissan",
    arLabel: "نيسان",
    logo: "/carlogo/nissan-logo.png",
  },
  {
    id: 32,
    enLabel: "porsche",
    arLabel: "بورش",
    logo: "/carlogo/porsche-logo.png",
  },
  {
    id: 33,
    enLabel: "suzuki",
    arLabel: "سوزوكي",
    logo: "/carlogo/suzuki-logo.png",
  },
  {
    id: 34,
    enLabel: "toyota",
    arLabel: "تويوتا",
    logo: "/carlogo/toyota-logo.png",
  },
  {
    id: 35,
    enLabel: "volkswagen",
    arLabel: "فولكسون",
    logo: "/carlogo/volkswagen-logo.png",
  },
  {
    id: 36,
    enLabel: "astonmartin",
    arLabel: "استون مارتن",
    logo: "/carlogo/astonmartin-logo.png",
  },
  {
    id: 40,
    enLabel: "cadillac",
    arLabel: "كاديلاك",
    logo: "/carlogo/cadillac-logo-alt.png",
  },
];
