export const cities = [
  { id: "1", cityAr: "ابهاء", cityEn: "Abha" },
  { id: "2", cityAr: "الباحة", cityEn: "Al-Baḥah" },
  { id: "3", cityAr: "الدمام", cityEn: "Al-Dammām" },
  { id: "4", cityAr: "الخبر", cityEn: "Al-Khubar" },
  { id: "5", cityAr: "الطايف", cityEn: "Al-Ṭaif" },
  { id: "6", cityAr: "بريدة", cityEn: "Buraydah" },
  { id: "7", cityAr: "الضهران", cityEn: "Dhahran" },
  { id: "8", cityAr: "حائل", cityEn: "Hail" },
  { id: "9", cityAr: "جدة", cityEn: "Jeddah" },
  { id: "10", cityAr: "جيزان", cityEn: "Jizan" },
  { id: "11", cityAr: "خميس مشيط", cityEn: "Khamis Mushayt" },
  { id: "12", cityAr: "مكة المكرمة", cityEn: "Mecca" },
  { id: "13", cityAr: "المدينة المنورة", cityEn: "Medina" },
  { id: "14", cityAr: "نجران", cityEn: "Najrān" },
  { id: "15", cityAr: "الرياض", cityEn: "Riyadh" },
  { id: "16", cityAr: "تبوك", cityEn: "Tabuk" },
  { id: "17", cityAr: "ينبع", cityEn: "Yanbu" },
];
